- name: Upload/generate certificates
  block:
    - name: Create SSL path
      file:
        path: "{{ elk_install_dir }}/nginx/ssl"
        state: directory
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
        mode: 0755

    - name: Upload certificates
      copy:
        src: "{{ cert }}"
        dest: "{{ elk_install_dir }}/nginx/ssl/{{ cert | basename }}"
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
        mode: 0640
        backup: true
      with_items:
        - "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.key"
        - "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.pem"
      loop_control:
        loop_var: cert

  rescue:
    - name: Generate certificates on ansible controller
      block:
        - name: Create local directory
          file:
            path: "{{ inventory_dir }}/credentials/nginx"
            state: directory
            mode: 0750

        - name: Generate self-signed certificates
          community.crypto.openssl_privatekey:
            path: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.key"

        - name: Create simple self-signed certificate
          community.crypto.x509_certificate:
            path: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.pem"
            privatekey_path: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.key"
            provider: selfsigned
      delegate_to: localhost
      become: false

    - name: Repeat tasks
      include_tasks: certificates.yml