---
- name: Print nginx configure args
  ansible.builtin.debug:
    msg: "{{ nginx_compile_args | sort }}"

- name: Generating nginx make files
  ansible.builtin.command: >-
    ./configure {{ nginx_compile_args | sort | join(' ') }}
  changed_when: nginx_compile_args_hash_result is changed
  args:
    chdir: "{{ elk_build_dir }}/{{ download_packages.nginx | basename | regex_replace('.tar.gz', '') }}"
  notify: Restart nginx

- name: Compile and install nginx
  community.general.make:
    chdir: "{{ elk_build_dir }}/{{ download_packages.nginx | basename | regex_replace('.tar.gz', '') }}"
    target: install
    jobs: "{{ ansible_processor_cores }}"
  notify: Restart nginx
