#SPDX-License-Identifier: MIT-0
---
# tasks file for install_nginx

- name: Tasks for nginx install
  block:
    - name: Checking if nginx configure args has been changed
      ansible.builtin.copy:
        content: "{{ nginx_compile_args_hash }}"
        dest: "{{ inventory_dir }}/files/nginx_compile_args_hash"
        mode: "0640"
      delegate_to: localhost
      register: nginx_compile_args_hash_result
      run_once: true

    - name: Install nginx
      ansible.builtin.import_tasks:
        file: install_nginx.yml
      when: >-
        nginx_compile_args_hash_result is changed
          or rebuild is true

    - name: Checking nginx service status
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Waiting for nginx service to be ready
      ansible.builtin.wait_for:
        port: 80
        timeout: 10

  rescue:
    - name: Prepare install nginx
      ansible.builtin.import_tasks:
        file: prepare_nginx.yml

    - name: Install nginx
      ansible.builtin.import_tasks:
        file: install_nginx.yml

  always:
    - name: Update certificates
      ansible.builtin.import_tasks:
        file: certificates.yml

    - name: Config nginx
      ansible.builtin.import_tasks:
        file: config_nginx.yml
