---
- name: Prepare nginx installation
  block:
    - name: Create paths for nginx
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        mode: "0750"
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
      with_items:
        - "{{ elk_install_dir }}/nginx/streams.d"
        - "{{ elk_install_dir }}/nginx/sites.d"
        - "{{ elk_logs_dir }}/nginx/"
        - "{{ elk_data_dir }}/nginx/cache"
      loop_control:
        loop_var: path

    - name: Extract nginx package to remote host
      ansible.builtin.import_role:
        name: global_tasks
        tasks_from: upload_and_download.yml
      vars:
        pkg_src: "{{ elk_local_package_path }}/{{ download_packages.nginx | basename }}"
        pkg_dst: "{{ elk_build_dir }}/{{ download_packages.nginx | basename | regex_replace('.tar.gz', '') }}"
        pkg_url: "{{ download_packages.nginx }}"
        pkg_bin: "{{ elk_build_dir }}/{{ download_packages.nginx | basename | regex_replace('.tar.gz', '') }}/sbin/nginx"

  rescue:
    - name: Download nginx
      ansible.builtin.get_url:
        url: "{{ download_packages.nginx }}"
        dest: "{{ elk_local_package_path }}/{{ download_packages.nginx | basename }}"
        mode: "0644"
      delegate_to: localhost
      become: false

    - name: Repeat
      ansible.builtin.include_tasks:
        file: install_nginx.yml
