---
- name: Prepare nginx installation
  block:
    - name: Create {{ elk_install_dir }}
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        mode: "0750"
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
      with_items:
        - "{{ elk_install_dir }}/nginx/streams.d"
        - "{{ elk_install_dir }}/nginx/sites.d"
        - "{{ elk_logs_dir }}/nginx/"
        - "{{ elk_build_dir }}/nginx/"
      loop_control:
        loop_var: path

    - name: Extract nginx package to remote host
      ansible.builtin.unarchive:
        src: "{{ elk_local_package_path }}/{{ download_packages.nginx | basename }}"
        dest: "{{ elk_build_dir }}"
        creates: "{{ elk_build_dir }}/{{ download_packages.nginx | basename | regex_replace('.tar.gz', '') }}"

    - name: Install yum packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - pcre-devel
        - zlib-devel
        - openssl-devel
      when: ansible_pkg_mgr in ('yum', 'dnf')
      become: true

  rescue:
    - name: Download nginx
      ansible.builtin.get_url:
        url: "{{ download_packages.nginx }}"
        dest: "{{ elk_local_package_path }}/{{ download_packages.nginx | basename }}"
        mode: "0644"
      delegate_to: localhost
      become: false

    - name: Repeat
      ansible.builtin.include_tasks:
        file: install_nginx.yml
