#SPDX-License-Identifier: MIT-0
---
# handlers file for install_nginx

- name: Configure nginx make file
  ansible.builtin.command: >-
    ./configure {{ nginx_configure_args | sort | join(' ') }}
  changed_when: true
  args:
    chdir: "{{ elk_install_dir }}/{{ download_elk_packages.nginx | basename | regex_replace('.tar.gz', '') }}"
  listen: Install nginx
  notify: Build and install nginx

- name: Build and install nginx
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ elk_install_dir }}/{{ download_elk_packages.nginx | basename | regex_replace('.tar.gz', '') }}"
  changed_when: true
  with_items:
    - make -j
    - make install
    - make clean
  notify: Restart nginx

- name: Test nginx config
  ansible.builtin.command: ./nginx -t
  changed_when: false
  args:
    chdir: "{{ elk_install_dir }}/nginx/sbin"
  listen:
    - Restart nginx
    - Reload nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  # notify: Wait for nginx to start

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  # notify: Wait for nginx to start
