#SPDX-License-Identifier: MIT-0
---
# handlers file for setup_systemd_service

- name: Restart polkit
  ansible.builtin.service:
    name: polkit
    state: restarted
    daemon_reload: true
    enabled: true

# - name: Reload systemd
#   ansible.builtin.systemd:
#     daemon_reload: true
