#SPDX-License-Identifier: MIT-0
---
# handlers file for setup_systemd_service

- name: Restart polkit
  ansible.builtin.service:
    name: polkit
    state: restarted
    daemon_reload: true
    enabled: true

- name: Systemd daemon reload
  ansible.builtin.service:
    name: "{{ elk_role }}"
    state: present
    daemon_reload: true
    enabled: true
