---
# Config sysctl
init_system_sysctl:
  vm.max_map_count: 262144
  vm.swappiness: 1
  vm.overcommit_memory: 1
  fs.file-max: 65536
  net.ipv4.ip_unprivileged_port_start: 80 # Allow non-root users to use port 80 and above

# Config user limits
init_system_ulimit:
  - "{{ elk_user }} - nofile 65536"
  - "{{ elk_user }} soft memlock unlimited"
  - "{{ elk_user }} hard memlock unlimited"

# TODO: Enable SSH key login
init_system_ssh_key_login: true

# Extra hosts
init_system_hosts: |-
  {% for host in (groups['all'] | sort) %}
  {{ hostvars[host]['ansible_host'] }}  {{ hostvars[host]['inventory_hostname'].rjust(20) }} {{ hostvars[host]['inventory_hostname'].rjust(20) }}.{{ elk_domain }}
  {% endfor %}

  {% for host in (keepalived_vrrp_instances | sort(attribute='virtual_ipaddress')) %}
  {{ host.virtual_ipaddress }}  {{ (host.name | lower).rjust(20) }}.{{ elk_domain }}
  {% endfor %}

init_system_packages:
  - when: "ansible_pkg_manager in ['dnf', 'yum']"
    packages:
      - bzip2
      - expect
      - net-tools
      - chrony
      - tar
      - gzip
      - readline-devel
      - patch
      - ncurses-devel
      - libaio-devel
      - glibc-devel
      - flex
      - bison
      - python3
      - python3-pip
      - wget
      - git
      - telnet
      - logrotate
      - crontabs
      - gcc
      - openssl-devel
      - make
      - unzip
      - bash-completion
