---
keepalived_configure_args:
  - --prefix={{ elk_install_dir }}/keepalived
  - --enable-log-file
  - --enable-json

keepalived_configure_args_hash: "{{ keepalived_configure_args | sort | hash('sha256') }}"

keepalived_vrrp_instances:
  - name: kibana
    master: "{{ groups['nginx'][0] }}"
    interface: eth1
    virtual_ipaddress: 192.168.56.253
    unicast_src_ip: 192.168.56.254
    check_script: /usr/bin/curl -s http://localhost:5601/api/status

  - name: logstash
    master: "{{ groups['nginx'][1] }}"
    interface: eth1
    virtual_ipaddress: 192.168.56.252
    unicast_src_ip: 192.168.56.254
    check_script: /bin/pidof nginx

  - name: elasticsearch
    master: "{{ groups['nginx'][0] }}"
    interface: eth1
    virtual_ipaddress: 192.168.56.251
    unicast_src_ip: 192.168.56.254
    check_script: /bin/pidof nginx

  - name: fleet-server
    master: "{{ groups['nginx'][1] }}"
    interface: eth1
    virtual_ipaddress: 192.168.56.250
    unicast_src_ip: 192.168.56.254
    check_script: /bin/pidof nginx

  - name: minio
    master: "{{ groups['nginx'][1] }}"
    interface: eth1
    virtual_ipaddress: 192.168.56.249
    unicast_src_ip: 192.168.56.254
    check_script: /bin/pidof nginx

keepalived_dependencies:
  yum:
    - gcc
    - openssl-devel
    - make

keepalived_options: -D
