---
# Must be per setting in one line
kibana_port: 5601

kibana_config:
  server.port: "{{ kibana_port }}"
  server.host: 0.0.0.0
  server.name: "{{ inventory_hostname | default(ansible_hostname) }}"
  csp.strict: true
  elasticsearch.requestTimeout: 90000
  logging.appenders.default.fileName: "{{ elk_logs_dir }}/kibana/kibana.log"
  logging.appenders.default.layout.type: json
  logging.appenders.default.policy.size: 256mb
  logging.appenders.default.policy.type: size-limit
  logging.appenders.default.strategy.max: 10
  logging.appenders.default.strategy.type: numeric
  logging.appenders.default.type: rolling-file
  xpack.security.session.lifespan: 7d
  xpack.security.session.idleTimeout: 3d
  xpack.security.encryptionKey: "{{ lookup('password', inventory_dir + '/credentials/kibana/security_encryptionKey length=32 chars=ascii_letters,digits') }}"
  xpack.encryptedSavedObjects.encryptionKey: "{{ lookup('password', inventory_dir + '/credentials/kibana/encryptedSavedObjects_encryptionKey length=32 chars=ascii_letters,digits')
    }}"
  path.data: "{{ elk_data_dir }}/kibana"
  server.publicBaseUrl: "https://kibana.{{ elk_domain }}"

kibana_gateway_url: "https://kibana.{{ elk_domain }}:{{ nginx_sites | selectattr('name', 'eq', 'kibana') | map(attribute='listen_port') | first }}"
