---
nginx_configure_args:
  - --prefix={{ elk_install_dir }}/nginx
  - --with-http_ssl_module
  - --with-http_v2_module
  - --with-http_v3_module
  - --with-http_stub_status_module
  - --with-http_gzip_static_module
  - --with-stream
  - --with-stream_ssl_module
  - --with-pcre
  - --with-poll_module
  - --http-log-path={{ elk_logs_dir }}/nginx/access.log

nginx_configure_args_hash: "{{ nginx_configure_args | sort | hash('sha256') }}"
