---
nginx_compile_args:
  - --prefix={{ elk_install_dir }}/nginx
  - --with-http_ssl_module
  - --with-http_v2_module
  - --with-http_v3_module
  - --with-http_stub_status_module
  - --with-http_gzip_static_module
  - --with-http_realip_module
  - --with-stream
  - --with-stream_ssl_module
  - --with-stream_realip_module
  - --with-threads
  - --with-pcre
  - --with-poll_module
  - --http-log-path={{ elk_logs_dir }}/nginx/access.log
  - --error-log-path={{ elk_logs_dir }}/nginx/error.log

nginx_compile_args_hash: "{{ nginx_compile_args | sort | trim | hash('md5') }}"

nginx_compile_tools:
  - gcc
  - pcre-devel
  - zlib-devel
  - openssl-devel

# Nginx certificates local path, if file not exists, self-sign certificates will be generated
# You can overwrite the auto-gen certificates by providing your own certificates
nginx_certificates:
  key: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.key"
  cert: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.crt"
  csr:
    file: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.csr"
    common_name: "{{ elk_domain }}"
    country_name: "CN"
    state_or_province_name: "Macau"
    locality_name: "Macau"
    organization_name: "CTI"
    organizational_unit_name: "IT"
    email_address: "haibin.li@technet.com.mo"
    authority_cert_issuer:
      - "DNS:{{ elk_domain }}"
      - "DNS:kibana.{{ elk_domain }}"
      - "DNS:elasticsearch.{{ elk_domain }}"
      - "DNS:minio.{{ elk_domain }}"
      - "DNS:logstash.{{ elk_domain }}"
      - "DNS:fleet-server.{{ elk_domain }}"
    authority_cert_serial_number: "0"
