---
nginx_sites:
  - name: elasticsearch
    listen_port: 443
    location: /
    upstreams: "{{ groups['elasticsearch'] }}"
    upstream_port: "{{ elasticsearch_http_port | default('9200') }}"
    upstream_method: least_conn
    proxy_ssl_verify: "off"
    proxy_protocol: https

  - name: kibana
    listen_port: 443
    location: /
    upstreams: "{{ groups['kibana'] }}"
    upstream_port: "{{ kibana_port | default('5601') }}"
    upstream_method: least_conn
    proxy_ssl_verify: "off"
    proxy_protocol: http # HTTP only, no HTTPS on the kibana side

  - name: fleet-server
    listen_port: 443
    location: /
    upstreams: "{{ groups['fleet_server'] }}"
    upstream_port: 8220
    upstream_method: least_conn
    proxy_ssl_verify: "off"
    proxy_protocol: https

  - name: minio
    listen_port: 443
    location: /
    upstreams: "{{ groups['minio'] }}"
    upstream_port: 9001
    upstream_method: least_conn
    proxy_ssl_verify: "off"
    proxy_protocol: http # HTTP only, no HTTPS on the minio side

nginx_streams:
  - name: elastic-agent
    listen_port: 15044
    upstreams: "{{ groups['logstash'] }}"
    upstream_port: 5044
    upstream_method: least_conn
    proxy_ssl_verify: "off"

  - name: logstash-input
    listen_port: 19800
    upstreams: "{{ groups['logstash'] }}"
    upstream_port: 9800
    upstream_method: least_conn
    proxy_ssl_verify: "off"

  # - name: elasticsearch-transport
  #   listen_port: 19300
  #   upstreams: "{{ groups['es_master'] }}"
  #   upstream_port: 9300
  #   upstream_method: least_conn
  #   proxy_ssl_verify: "off"

nginx_compile_args:
  - --prefix={{ elk_install_dir }}/nginx
  - --with-http_ssl_module
  - --with-http_v2_module
  - --with-http_v3_module
  - --with-http_stub_status_module
  - --with-http_gzip_static_module
  - --with-stream
  - --with-stream_ssl_module
  - --with-pcre
  - --with-poll_module
  - --http-log-path={{ elk_logs_dir }}/nginx/access.log

nginx_compile_args_hash: "{{ nginx_compile_args | sort | trim | hash('md5') }}"

nginx_compile_tools:
  - gcc
  - pcre-devel
  - zlib-devel
  - openssl-devel

# Nginx certificates local path, if file not exists, self-sign certificates will be generated
# You can overwrite the auto-gen certificates by providing your own certificates
nginx_certificates:
  key: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.key"
  cert: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.crt"
  ca: "{{ inventory_dir }}/credentials/nginx/{{ elk_domain }}.ca"
