# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.ssh.insert_key = false

  # How many vm do you want?
  N = 13

  # What OS do you want to use?
  VMBOX = "bento/rockylinux-8.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024 * 4
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    vb.linked_clone = true
    vb.check_guest_additions = false
  end

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
    sed -i "s|PasswordAuthentication no|PasswordAuthentication yes|g" /etc/ssh/sshd_config
    echo "nameserver 8.8.8.8" | tee -a /etc/resolv.conf
    echo "nameserver 223.5.5.5" | tee -a /etc/resolv.conf
    echo "NETWORKING_IPV6=no" | tee -a /etc/sysconfig/network
    echo "IPV6INIT=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "IPV6_AUTOCONF=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "IPV6_DEFROUTE=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "IPV6_PEERDNS=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "IPV6_PEERROUTES=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "IPV6FORWARDING=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "IPV6_AUTOTUNNEL=no" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth1

    timedatectl set-timezone "Asia/Shanghai"
    timedatectl status

    dnf install -y epel-release
    /usr/bin/crb enable

    dnf install -y bzip2 expect net-tools chrony tar gzip readline-devel \
      patch ncurses-devel libaio-devel glibc-devel flex bison nano htop \
      byobu python3 python3-pip

     /bin/systemctl restart NetworkManager.service
    /bin/systemctl restart sshd.service
    SHELL
  end

  #Disabling the default /vagrant share
  config.vm.synced_folder ".", "/vagrant", disabled: true

  (1..N).each do |i|
    config.vm.define "elk#{i}" do |node|
      node.vm.box = "#{VMBOX}"
      node.vm.network "private_network", ip: "192.168.56.#{10+i}"
    end
  end
end
