---
# handlers file for keepalived
- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Reload keepalived
  ansible.builtin.service:
    name: keepalived
    state: reloaded
    enabled: true
    daemon_reload: true
  become: true
