---
- name: Enroll new nodes into the cluster
  block:
    - name: Import config tasks
      ansible.builtin.include_role:
        name: config_{{ elk_role }}

    - name: Enroll node '{{ inventory_hostname | default(ansible_host) }}'
      ansible.builtin.command:
        argv:
          - "{{ elk_install_dir }}/elasticsearch/bin/elasticsearch"
          - --pidfile
          - "{{ elk_logs_dir }}/elasticsearch/elasticsearch.pid"
          - --daemonize
          - --enrollment-token
          - "{{ elk_enrollment_token }}"
      changed_when: false
      register: enrollment_status

    - name: Wait for node to be started
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 9200
        timeout: 300

  rescue:
    - name: Skip security auto config
      ansible.builtin.debug:
        msg: "{{ enrollment_token.stderr }}"
      when:
        - enrollment_token.stderr is defined
        - "'Skipping security auto config' in enrollment_token.stderr"
