---
- name: Install {{ elk_role }}
  block:
    - name: Create remote paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
      vars:
        create_paths:
          - "{{ elk_data_dir }}/{{ elk_role }}"
          - "{{ elk_logs_dir }}/{{ elk_role }}"
          - "{{ elk_pkgs_dir }}"
          - "{{ elk_install_dir }}"
      loop: "{{ create_paths | sort }}"

    - name: Extract package to {{ elk_install_dir + '/' + elk_role + '-' + elk_version }}
      ansible.builtin.import_role:
        name: global_tasks
        tasks_from: upload_and_download.yml
      vars:
        pkg_src: "{{ elk_local_package_path }}/{{ elk_role }}/{{ elk_package_full_name }}"
        pkg_dst: "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}"
        pkg_url: "{{ elk_package_url }}"
        pkg_bin: "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}/bin/{{ elk_role }}"

    - name: Update soft link under {{ elk_install_dir + '/' + elk_role }}
      ansible.builtin.file:
        src: "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}"
        dest: "{{ elk_install_dir }}/{{ elk_role }}"
        state: link

    - name: Remove unused paths
      ansible.builtin.file:
        path: "{{ remove_path }}"
        state: absent
      with_items:
        - "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}/data"
        - "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}/logs"
      loop_control:
        loop_var: remove_path

    - name: Create soft link under {{ elk_install_dir + '/' + elk_role }}
      ansible.builtin.file:
        src: "{{ link_path.src }}"
        dest: "{{ link_path.dest }}"
        state: link
      with_items:
        - src: "{{ elk_data_dir }}/{{ elk_role }}"
          dest: "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}/data"
        - src: "{{ elk_logs_dir }}/{{ elk_role }}"
          dest: "{{ elk_install_dir }}/{{ elk_role }}-{{ elk_version }}/logs"
      loop_control:
        loop_var: link_path

  rescue:
    - name: Create local packages path under {{ elk_local_package_path }}
      ansible.builtin.file:
        path: "{{ elk_local_package_path }}/{{ elk_role }}"
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: Print tips
      ansible.builtin.debug:
        msg: Downloading from {{ elk_package_url }}, please wait...

    - name: Downloading...
      ansible.builtin.get_url:
        url: "{{ elk_package_url }}"
        dest: "{{ elk_local_package_path }}/{{ elk_role }}/"
        mode: "0444"
      delegate_to: localhost
      register: download_package
      until: download_package is succeeded
      retries: 3
      delay: 10

    - name: Repeat install {{ elk_role }}
      ansible.builtin.include_tasks:
        file: install.yml
