#SPDX-License-Identifier: MIT-0
---
# tasks file for install_elk

- name: Set package info
  ansible.builtin.set_fact:
    elk_package_url: "{{ package.value }}"
    elk_package_full_name: "{{ package.value | basename }}"
    elk_package_short_name: "{{ package.value | basename | replace('.tar.gz', '') }}"
  with_dict: "{{ download_packages }}"
  loop_control:
    loop_var: package
    label: "{{ package.value | basename }}"
  when: package.key == elk_role

- name: Import install tasks
  ansible.builtin.import_tasks:
    file: install.yml

- name: Import config tasks
  ansible.builtin.include_role:
    name: config_{{ elk_role }}

- name: Tasks for group "'elasticsearch'
  when: "'elasticsearch' in group_names"
  ansible.builtin.import_tasks:
    file: elasticsearch.yml

- name: Tasks for group "'kibana'
  when: "'kibana' in group_names"
  ansible.builtin.import_tasks:
    file: kibana.yml
