---
- name: Update password for user '{{ built_in_user }}'
  ansible.builtin.command:
    argv:
      - "{{ elk_install_dir }}/elasticsearch/bin/elasticsearch-reset-password"
      - --batch
      - --silent
      - --username
      - "{{ built_in_user }}"
  changed_when: false
  register: elastic_password

- name: Copy password to local file {{ inventory_dir + '/credentials/passwords/passwd_' + built_in_user }}
  ansible.builtin.copy:
    content: "{{ elastic_password.stdout }}"
    dest: "{{ inventory_dir }}/credentials/passwords/passwd_{{ built_in_user }}"
    mode: "0600"
  become: false
  delegate_to: localhost
