#SPDX-License-Identifier: MIT-0
---
# handlers file for install_nginx

- name: Test nginx config
  ansible.builtin.command: ./nginx -t
  changed_when: false
  args:
    chdir: "{{ elk_install_dir }}/nginx/sbin"
  listen:
    - Restart nginx
    - Reload nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Wait for nginx to start
  ansible.builtin.wait_for:
    port: 80
    timeout: 120
  listen:
    - Restart nginx
    - Reload nginx
