---
- name: Compare keystore
  ansible.builtin.shell: |
    set -o pipefail
    {{ elk_install_dir }}/kibana/bin/kibana-keystore \
      show \
      {{ keystore.key }} \
      || echo "Not found"
  changed_when: false
  register: keystore_chk

- name: Update keystore
  ansible.builtin.shell: |
    set -o pipefail
    echo $CERT_PASSWORD | {{ elk_install_dir }}/kibana/bin/kibana-keystore add --stdin --force {{ keystore.key }}
  environment:
    CERT_PASSWORD: "{{ keystore.value }}"
  vars:
    same_password: "{{ keystore_chk.stdout_lines[:-1] != keystore.value }}"
  changed_when: not same_password
  when: not same_password
