---
- name: Print body content
  ansible.builtin.debug:
    msg: |
      {{ elasticsearch_api_body }}

- name: Requesting '{{ elasticsearch_gateway_url }}/{{ elasticsearch_api_path | default('') }}'
  ansible.builtin.uri:
    url: "{{ elasticsearch_gateway_url }}/{{ elasticsearch_api_path | default('') }}"
    method: "{{ elasticsearch_api_method | default('GET') }}"
    url_username: "{{ elasticsearch_api_user | default('elastic') }}"
    url_password: "{{ elasticsearch_api_pass | default(elasticsearch_elastic_password) }}"
    force_basic_auth: true
    return_content: true
    validate_certs: false
    body_format: json
    body: |
      {{ elasticsearch_api_body | default('') }}
    status_code:
      - 200
      - 201
  register: es_api_response
