---
- name: Get cluster status
  ansible.builtin.import_role:
    name: config_elasticsearch
    tasks_from: api.yml
  vars:
    elasticsearch_api_path: "_cluster/health?wait_for_status=yellow&timeout=600s"
    elasticsearch_api_status_code:
      - 200
      - 502
      - "-1"

- name: Set elasticsearch_bootstrap_enabled to {{ (es_api_response.status == 200) | ternary('false', 'true') }}
  ansible.builtin.set_fact:
    elasticsearch_bootstrap_enabled: "{{ (es_api_response.status == 200) | ternary('false', 'true') }}"
