#SPDX-License-Identifier: MIT-0
---
# tasks file for pre_tasks

- name: Gather all nodes facts
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Import variables
  ansible.builtin.include_vars: "{{ item }}"
  with_fileglob:
    - "{{ playbook_dir }}/vars/*.yml"
    - "{{ inventory_dir }}/vars/*.yml"

- name: Print config
  ansible.builtin.debug:
    msg: "{{ elasticsearch_config }}"
  when: "'elasticsearch' in group_names"

- name: Check cluster status
  ansible.builtin.import_tasks:
    file: check_cluster_status.yml
  run_once: true
