#SPDX-License-Identifier: MIT-0
---
# tasks file for pre_tasks

- name: Gather all nodes facts
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Import variables
  ansible.builtin.include_vars: "{{ item }}"
  with_fileglob:
    - "{{ playbook_dir }}/vars/*.yml"
    - "{{ inventory_dir }}/vars/*.yml"

- name: Set some runtime variables
  ansible.builtin.set_fact:
    nginx_vrrp_address: "{{ keepalived_vrrp_instances | selectattr('name', 'equalto', 'NGINX') | map(attribute='virtual_ipaddress') | first }}"

- name: Check cluster status
  ansible.builtin.import_tasks:
    file: check_cluster_status.yml
  run_once: true
  when: "'elasticsearch' in group_names"
