---
# tasks file for keepalived
- name: Install/config keepalived
  block:
    - name: Checking service status
      ansible.builtin.service:
        name: keepalived
        state: started

    - name: Checking if keepalived configure args has been changed
      ansible.builtin.copy:
        content: "{{ keepalived_configure_args_hash }}"
        dest: "{{ inventory_dir }}/files/keepalived_{{ inventory_hostname }}_configure_args_hash"
        mode: "0640"
      delegate_to: localhost
      register: keepalived_configure_args_hash_result
      become: false

    - name: Re-install keepalived
      ansible.builtin.import_tasks:
        file: install_keepalived.yml
      when: keepalived_configure_args_hash_result is changed or rebuild

    - name: Config keepalived
      ansible.builtin.import_tasks: config_keepalived.yml

  rescue:
    - name: Install keepalived
      ansible.builtin.import_tasks:
        file: install_keepalived.yml

    - name: Config keepalived
      ansible.builtin.import_tasks: config_keepalived.yml
