#SPDX-License-Identifier: MIT-0
---
# tasks file for elastic_certificates

- name: Create path for certificates
  ansible.builtin.file:
    path: "{{ elk_certificates_path }}"
    state: directory
    mode: "0750"
    owner: "{{ elk_user }}"
    group: "{{ elk_group }}"

- name: Certificates
  ansible.builtin.import_tasks:
    file: certificates.yml
