---
# tasks file for minio
- name: Deploy/config minio
  block:
    - name: Check minio service status
      ansible.builtin.service:
        name: minio
        state: started

    - name: Check minio service ports
      ansible.builtin.wait_for:
        port: "{{ minio_port }}"
        state: started
        timeout: 10
      with_items:
        - 9000
        - 9001
      loop_control:
        loop_var: minio_port

  rescue:
    - name: Check minio devices count
      ansible.builtin.fail:
        msg: Minio devices count must be greater than 0
      when: (minio_devices | length) < 1

    - name: Config storages
      ansible.builtin.include_tasks:
        file: storages.yml
      loop: "{{ minio_devices }}"
      loop_control:
        loop_var: device
        extended: true

    - name: Install minio
      ansible.builtin.import_tasks:
        file: install.yml

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Config minio
  ansible.builtin.import_tasks:
    file: config_main.yml
