---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Config /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |-
      {{ init_system_hosts }}
    mode: "0644"
    owner: "{{ elk_user }}"
    group: "{{ elk_group }}"
    create: true
    backup: true
