---
- name: "Update {{ elk_data_dir }}/logstash/logstash_keystore_pass"
  ansible.builtin.copy:
    content: "{{ logstash_keystore_password }}"
    dest: "{{ elk_data_dir }}/logstash/logstash_keystore_pass"
    owner: "{{ elk_user }}"
    group: "{{ elk_group }}"
    mode: "0600"
  no_log: true

- name: Create keystore file if not exists
  ansible.builtin.command:
    argv:
      - "{{ elk_install_dir }}/logstash/bin/logstash-keystore"
      - "create"
    creates: "{{ elk_install_dir }}/logstash/config/logstash.keystore"
  environment:
    LOGSTASH_KEYSTORE_PASS: "{{ logstash_keystore_password }}"
  notify: Restart logstash

- name: Add logstash keystores
  ansible.builtin.command:
    argv:
      - "echo"
      - "{{ keystore.value }}"
      - "|"
      - "{{ elk_install_dir }}/logstash/bin/logstash-keystore"
      - "add"
      - "{{ keystore.key | upper }}"
      - "--stdin"
  changed_when: false
  with_dict: "{{ logstash_keystores }}"
  loop_control:
    loop_var: keystore
    label: "{{ keystore.key }}"
  environment:
    LOGSTASH_KEYSTORE_PASS: "{{ logstash_keystore_password }}"
