---
- name: Install nginx
  block:
    - name: Create {{ elk_install_dir }}
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        mode: "0750"
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
      with_items:
        - "{{ elk_install_dir }}"
        - "{{ elk_logs_dir }}/nginx/"
      loop_control:
        loop_var: path

    - name: Extract nginx package to remote host
      ansible.builtin.unarchive:
        src: "{{ elk_local_package_path }}/{{ download_elk_packages.nginx | basename }}"
        dest: "{{ elk_install_dir }}"
        creates: "{{ elk_install_dir }}/{{ download_elk_packages.nginx | basename | regex_replace('.tar.gz', '') }}"
      notify: Install nginx

    - name: Install yum packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - pcre-devel
        - zlib-devel
        - openssl-devel
      when: ansible_pkg_mgr in ('yum', 'dnf')
      become: true
      notify: Install nginx

  rescue:
    - name: Download nginx
      ansible.builtin.get_url:
        url: "{{ download_elk_packages.nginx }}"
        dest: "{{ elk_local_package_path }}/{{ download_elk_packages.nginx | basename }}"
        mode: "0644"
      delegate_to: localhost
      become: false

    - name: Repeat
      ansible.builtin.include_tasks:
        file: install_nginx.yml
