#SPDX-License-Identifier: MIT-0
---
# tasks file for install_nginx

- name: Tasks for nginx install
  block:
    - name: Checking if nginx configure args has been changed
      ansible.builtin.copy:
        content: "{{ nginx_configure_args_hash }}"
        dest: "{{ inventory_dir }}/files/nginx_configure_args_hash"
        mode: "0640"
      delegate_to: localhost
      run_once: true
      notify: Install nginx

    - name: Print nginx configure args
      ansible.builtin.debug:
        var: nginx_configure_args | sort

    # - name: Checking nginx service status
    #   ansible.builtin.service:
    #     name: nginx
    #     state: started

    - name: Update nginx config
      ansible.builtin.template:
        src: nginx/nginx.conf.j2
        dest: "{{ elk_install_dir }}/nginx/nginx.conf"
        mode: "0640"
        owner: "{{ elk_user }}"
        group: "{{ elk_group }}"
        validate: "{{ elk_install_dir }}/nginx/sbin/nginx -t -c %s"
      notify: Restart nginx

  rescue:
    - name: Install nginx
      ansible.builtin.import_tasks:
        file: install_nginx.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
