---
- name: Gather all nodes facts
  hosts: all
  become: false
  gather_facts: false
  roles:
    - role: pre_tasks
      run_once: true

- name: Install ELK cluster
  hosts: elasticsearch:kibana:logstash
  become: false
  gather_facts: false
  serial: 1
  roles:
    - role: install_elk
      vars:
        elk_role: elasticsearch
      when: "'elasticsearch' in group_names"

    - role: install_nginx
      when: "'nginx' in group_names"

    - role: install_elk
      vars:
        elk_role: kibana
      when: "'kibana' in group_names"

    - role: install_elk
      vars:
        elk_role: logstash
      when: "'logstash' in group_names"
