---
- name: Gather all nodes facts
  hosts: all
  become: false
  gather_facts: false
  run_once: true
  roles:
    - role: pre_tasks
      tags: always

- name: Bootstrap ELK cluster
  hosts: es_master
  become: false
  gather_facts: false
  roles:
    - role: install_elk
      vars:
        elk_role: elasticsearch
      tags: elasticsearch
      when: ansible_host == elasticsearch_bootstrap_host

- name: Deploy ELK master nodes
  hosts: es_master
  become: false
  gather_facts: false
  serial: 1
  roles:
    - role: install_elk
      vars:
        elk_role: elasticsearch
      tags: elasticsearch
      when:
        - ansible_host != elasticsearch_bootstrap_host

- name: Deploy ELK nodes
  hosts: elasticsearch:!es_master
  become: false
  gather_facts: false
  serial: 1
  roles:
    - role: install_elk
      vars:
        elk_role: elasticsearch
      tags: elasticsearch

- name: Deploy Kibana
  hosts: kibana
  become: false
  gather_facts: false
  serial: 1
  roles:
    - role: install_elk
      vars:
        elk_role: kibana
      tags: kibana

- name: Deploy Logstash
  hosts: logstash
  become: false
  gather_facts: false
  serial: 1
  roles:
    - role: install_elk
      vars:
        elk_role: logstash
      tags: logstash
