---
- name: Gather all nodes facts
  hosts: elk
  become: false
  gather_facts: false
  run_once: true
  roles:
    - role: pre_tasks

- name: Config ES masters
  hosts: es_master
  serial: 1
  become: false
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: config_elasticsearch
      tags: elasticsearch

- name: Config ES nodes
  hosts: elasticsearch:!es_master
  serial: 1
  become: false
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: config_elasticsearch
      tags: elasticsearch

- name: Config Kibana
  hosts: kibana
  serial: 1
  become: false
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: config_kibana
      tags: kibana

- name: Config Logstash
  hosts: logstash
  serial: 1
  become: false
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: config_logstash
      tags: logstash
