---
- name: Gather all nodes facts
  hosts: elk
  become: false
  gather_facts: false
  run_once: true
  roles:
    - role: pre_tasks

- name: Config ES masters
  hosts: es_master
  serial: 1
  become: false
  gather_facts: false
  module_defaults:
    ansible.builtin.uri:
      url_username: elastic
      url_password: "{{ lookup('file', inventory_dir + '/credentials/passwords/passwd_elastic') }}"
      force_basic_auth: true
      validate_certs: false
      return_content: true
  roles:
    - role: config_elasticsearch
      tags: elasticsearch

- name: Config ES nodes
  hosts: elasticsearch:!es_master
  serial: 1
  become: false
  gather_facts: false
  module_defaults:
    ansible.builtin.uri:
      url_username: elastic
      url_password: "{{ lookup('file', inventory_dir + '/credentials/passwords/passwd_elastic') }}"
      force_basic_auth: true
      validate_certs: false
      return_content: true
  roles:
    - role: config_elasticsearch
      tags: elasticsearch

- name: Config Kibana
  hosts: kibana
  serial: 1
  become: false
  gather_facts: false
  module_defaults:
    ansible.builtin.uri:
      url_username: elastic
      url_password: "{{ lookup('file', inventory_dir + '/credentials/passwords/passwd_elastic') }}"
      force_basic_auth: true
      validate_certs: false
      return_content: true
  roles:
    - role: config_kibana
      tags: kibana

- name: Config Logstash
  hosts: logstash
  serial: 1
  become: false
  gather_facts: false
  roles:
    - role: config_logstash
      tags: logstash
