---
- name: Reset Elasticsearch user password
  hosts: es_master[0]
  become: false
  vars_prompt:
    - name: confirm_reset
      prompt: This playbook will reset the password for the built-in users. Are you sure?(no/yes)
      private: false
      default: "no"
  pre_tasks:
    - name: Run pre-tasks
      ansible.builtin.import_role:
        name: pre_tasks

    - name: Reset Elasticsearch user password
      ansible.builtin.include_role:
        name: install_elk
        tasks_from: update_built_in_users_password.yml
      with_items:
        - apm_system
        - beats_system
        - elastic
        - kibana_system
        - logstash_system
        - remote_monitoring_user
      loop_control:
        loop_var: built_in_user
      when: confirm_reset == "yes"

  roles:
    - report