---
- name: Prepare OS system
  ansible.builtin.import_playbook: 00-prepare.yml

- name: Deploy ELK
  ansible.builtin.import_playbook: 01-install-elk.yml

- name: Config ELK
  ansible.builtin.import_playbook: 02-config-elk.yml
