---
- name: Prepare OS system
  ansible.builtin.import_playbook: 00-prepare.yml

- name: Install nginx and keepalived
  ansible.builtin.import_playbook: 01-nginx-keepalived.yml

- name: Deploy/config minio
  ansible.builtin.import_playbook: 02-minio.yml

- name: Deploy ELK
  ansible.builtin.import_playbook: 03-install-elk.yml

- name: Config ELK
  ansible.builtin.import_playbook: 04-config-elk.yml

- name: Create report files
  ansible.builtin.import_playbook: 82-report.yml
