# This is a docker-compose file for Semaphore with semaphore user
services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphore:non-root
    container_name: semaphore
    hostname: semaphore
    restart: unless-stopped
    build:
      context: .
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: P@ssw0rd
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: haibin.li@technet.com.mo
      SEMAPHORE_DB_PATH: /home/semaphore/data
      SEMAPHORE_CONFIG_PATH: /home/semaphore/config
      TZ: Asia/Shanghai
    user: semaphore
    volumes:
      - semaphore_config:/home/semaphore/config
      - semaphore_data:/home/semaphore/data
      - semaphore_tmp:/home/semaphore/tmp
      - $PWD/../:/workdir
    working_dir: /workdir

volumes:
  semaphore_config:
  semaphore_data:
  semaphore_tmp: