---
- name: Compare keystore {{ keystore.key }}
  ansible.builtin.shell: |
    set -o pipefail
    {{ elk_install_dir }}/elasticsearch/bin/elasticsearch-keystore \
      show \
      {{ keystore.key }} \
      || echo "Not found"
  changed_when: false
  register: keystore_chk

- name: Update keystore {{ keystore.key }}
  ansible.builtin.shell: |
    set -o pipefail
    echo $CERT_PASSWORD | {{ elk_install_dir }}/elasticsearch/bin/elasticsearch-keystore add --stdin --force {{ keystore.key }}
  environment:
    CERT_PASSWORD: "{{ keystore.value }}"
  changed_when: keystore_chk.stdout != keystore.value
  when:
    - keystore_chk.stdout != keystore.value
  notify: Restart elasticsearch

# - name: Reload nodes secure settings
#   uri:
#     url: "{{ elasticsearch_gateway_url }}/_nodes/reload_secure_settings"
#     method: POST
#     url_username: "elastic"
#     url_password: "{{ elasticsearch_elastic_password }}"
#     body_format: json
#     body: |
#       {
#         "{{ keystore.key }}": "{{ keystore.value }}"
#       }

# - name: Reload nodes secure settings
#   ansible.builtin.include_tasks: api.yml
#   with_dict: "{{ elasticsearch_snapshot_repos }}"
#   loop_control:
#     loop_var: repo
#     label: "{{ repo.key }}"
#   vars:
#     elasticsearch_api_method: "POST"
#     elasticsearch_api_path: "_nodes/reload_secure_settings"
#     elasticsearch_api_body: |
#       {
#         "{{ keystore.key }}": "{{ keystore.value }}"
#       }
