#SPDX-License-Identifier: MIT-0
---
# tasks file for config_elasticsearch

# CAUTION: DO NOT change the `marker` value in the blockinfile module
- name: Update elasticsearch.yml
  ansible.builtin.blockinfile:
    path: "{{ elk_install_dir }}/elasticsearch/config/elasticsearch.yml"
    block: "{{ elasticsearch_config | to_nice_yaml }}"
    marker: "#-------------------------- {mark} ANSIBLE MANAGED BLOCK --------------------------"
  notify: Restart elasticsearch
  when: elasticsearch_config is defined
