---
- name: Get snapshot repository info
  ansible.builtin.include_tasks: api.yml
  vars:
    elasticsearch_api_path: "_snapshot/{{ elasticsearch_minio_snapshot_bucket }}?pretty"
    elasticsearch_api_status_code:
      - 200
      - 404

- name: Verify snapshot repository
  ansible.builtin.uri:
    url: "{{ kibana_gateway_url }}/api/snapshot_restore/repositories/{{ elasticsearch_minio_snapshot_bucket }}/verify"
  register: snapshot_repository_verify
  failed_when: snapshot_repository_verify.json.verification.error.message is defined
  when: es_api_response.status == 200

- name: Print verification error message
  ansible.builtin.debug:
    msg: "{{ snapshot_repository_verify.json.verification.error.message }}"
  when: snapshot_repository_verify.json.verification.error.message is defined

- name: Update snapshot repository
  ansible.builtin.include_tasks: api.yml
  with_dict: "{{ elasticsearch_snapshot_repos }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.key }}"
  vars:
    elasticsearch_api_method: "{{ repo.enabled | default(true) | ternary('PUT', 'DELETE') }}"
    elasticsearch_api_path: "_snapshot/{{ repo.key }}?pretty"
    elasticsearch_api_body: "{{ lookup('template', 'elasticsearch/snapshot_repository.json.j2') }}"
  when: es_api_response.status != 200
